# Generated by Django 4.1 on 2023-07-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_indexmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideimg',
            options={'verbose_name_plural': 'Добавить фотографии в карусель'},
        ),
    ]
